[package]
name = "neige-http"
version = "0.1.0"
license = "MIT"
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
